#!/bin/sh

#批量转换音频等至ogg
#第一个参数为储存有所有要转码的文件的路径的列表文件
#第二个参数为制定输出的目录，默认为"./out"

#判断是否给定列表文件
if [ "$1" = "" ]
then
	echo "no input list file"
	exit
fi

#判断列表文件是否存在
if [ ! -e "$1" ]
then
	echo "list file doesn't exist"
	exit
fi

#判断是否给定输出目录
#默认输出目录为out
if [ "$2" = "" ]
then
	dir="out"
else
	dir="$2"
fi
if [ ! -d "$dir" ]
then
	mkdir -p "$dir"
fi
echo "output dir:$dir" 

#指定缓存目录
buffdir="transogg$$"

#建立缓存目录到系统默认内存文件系统
if [ ! -d "/dev/shm/$buffdir" ]
then
	mkdir -p "/dev/shm/$buffdir"
fi

#删除缓存，保证程序正常工作
if [ -e "/dev/shm/$buffdir/transogg_buff.wav" ]
then
	rm "/dev/shm/$buffdir/transogg_buff.wav"
fi

if [ -e "/dev/shm/$buffdir/transogg_buff.ogg" ]
then
	rm "/dev/shm/$buffdir/transogg_buff.ogg"
fi

#初始化变量
transed=0
existed=0
notexist=0
n=1
fileline=`expr \`cat $1 | wc -l\` + 1`
filename=`sed -n "$n,$n p" "$1"`

echo "list file: $1"

#遍历列表文件
echo ""
while [ ! "$n" = "$fileline" ]
do
	#判断行是否为空
	if [ "$filename" = "" ]
	then
		#如果为空
		#输出信息
		echo "line $n is null"
		#结束本次循环
		n=`expr $n + 1`
		filename=`sed -n "$n,$n p" "$1"`
		continue
	fi
	
	#判断文件是否存在
	if [ ! -e "./$filename" ]
	then
		#如果不存在
		#打印文件不存在
		echo "file $filename doesn't exist!"
		
		#结束本次循环
		notexist=`expr $notexist + 1`
		n=`expr $n + 1`
		filename=`sed -n "$n,$n p" "$1"`
		continue
	fi
	
	
	#判断文件是否已转码
	if [ -e "$dir/${filename%.*}.ogg" ]
	then
		#如果已经转码
		#输出信息
		echo "file \"$dir/${filename%.*}.ogg\" are already existing"
		#结束本次循环
		n=`expr $n + 1`
		filename=`sed -n "$n,$n p" "$1"`
		existed=`expr $existed + 1`
		continue
	fi
	
	#如果检查全部通过
	
	#输出信息
	echo "#---------------------------------------------#"
	echo "#translating the $n th file \"$filename\"#"
	echo "#---------------------------------------------#"
	
	#开始转码
	
	#生成中间文件到系统默认的内存文件目录
	#mplayer -really-quiet "$filename" -vo null -ao pcm:file="/dev/shm/$buffdir/buff.wav" 2>/dev/null
	#oggenc "/dev/shm/$buffdir/buff.wav" -o "/dev/shm/$buffdir/buff.ogg"
	ffmpeg -i "$filename" -vn -acodec libvorbis "/dev/shm/$buffdir/buff.ogg"
	
	#移动目标文件到目标目录
	filename=${filename##*/}
	mv "/dev/shm/$buffdir/buff.ogg" "$dir/${filename%.*}.ogg"
	echo "#file translate conplite#"
	echo ""
	
	#删除中间文件
	rm "/dev/shm/$buffdir/buff.wav"
	
	#结束本次循环
	n=`expr $n + 1`
	filename=`sed -n "$n,$n p" "$1"`
	transed=`expr $transed + 1`
done

#删除缓存目录
if [ `ls -A "/dev/shm/$buffdir" | wc -l` = 0 ]
then
	rmdir "/dev/shm/$buffdir"
fi

#打印转码统计
echo "trans comlite"
echo "translated $transed file"
echo "exising $existed file"
echo "not exist $notexist file"
