#!/bin/sh

#批量转换音频等至ogg
#第一个参数为储存有所有要转码的文件的路径的列表文件
#第二个参数为制定输出的目录，默认为"./out"

#判断是否给定列表文件
if [ "$1" = "" ]
then
	echo "no input list file"
	exit
fi

#判断列表文件是否存在
if [ -d "$1" ]
then
	echo "list file doesn't exist"
	exit
fi

#判断是否给定输出目录
#默认输出目录为out
if [ "$2" = "" ]
then
	dir="out"
else
	dir="$2"
fi
if [ ! -d "$dir" ]
then
	mkdir "$dir"
fi
echo "output dir:$dir" 

#删除缓存，保证程序正常工作
if [ -d "/dev/shm/transogg_buff.wav" ]
then
	rm /dev/shm/transogg_buff.wav
fi

if [ -d "/dev/shm/transogg_buff.ogg" ]
then
	rm /dev/shm/transogg_buff.ogg
fi

#初始化变量
transed=0
existed=0
notexist=0
n=1
fileline=`expr \`cat $1 | wc -l\` + 1`
filename=`sed -n "$n,$n p" "$1"`

echo "list file: $1"

#遍历列表文件
echo ""
while [ ! "$n" = "$fileline" ]
do
	#判断行是否为空
	if [ "$filename" = "" ]
	then
		#如果为空
		#输出信息
		echo "line $n is null"
		#结束本次循环
		n=`expr $n + 1`
		filename=`sed -n "$n,$n p" "$1"`
		continue
	fi
	
	#判断文件是否存在
	if [ -d "$filename" ]
	then
		#如果不存在
		#打印文件不存在
		echo "file $filename doesn't exist!"
		#结束本次循环
		notexist=`expr $notexist + 1`
		n=`expr $n + 1`
		filename=`sed -n "$n,$n p" "$1"`
		continue
		
	fi

	
	#判断文件是否已转码
	if [ ! -d "$dir/${filename%.*}.ogg" ]
	then
		#如果已经转码
		#输出信息
		echo "#file \"${filename%.*}.ogg\" existing#"
		#结束本次循环
		n=`expr $n + 1`
		filename=`sed -n "$n,$n p" "$1"`
		existed=`expr $existed + 1`
		continue
	fi
	
	#如果检查全部通过
	#输出信息
	echo ""
	echo "#---------------------------------------------#"
	echo "#translating the $n th file $filename#"
	echo "#---------------------------------------------#"
	echo ""
	#开始转码
	#生成中间文件到系统默认的内存文件目录
	mplayer "$filename" -ao pcm:file=/dev/shm/buff.wav
	oggenc /dev/shm/buff.wav -o /dev/shm/buff.ogg
	#移动目标文件到目标目录
	echo ""
	echo "#file translate conplite#"
	echo "#copying file#"
	mv /dev/shm/buff.ogg "$dir/${filename%.*}.ogg"
	echo "#copy file complite#"
	echo ""
	#删除中间文件
	rm /dev/shm/buff.wav
	#结束本次循环
	n=`expr $n + 1`
		filename=`sed -n "$n,$n p" "$1"`
	transed=`expr $transed + 1`
done

#打印转码统计
echo "trans comlite"
echo "translated $transed file"
echo "exising $existed file"
echo "not exist $notexist file"
